#!/bin/sh
set -e
. /usr/share/debconf/confmodule

# Fetch all network interfaces except 'lo'
INTERFACES=$(ip -o link show | awk -F': ' '{print $2}' | grep -v 'lo' | tr '
' ',' | sed 's/,$//' | sed 's/,/, /g')

# Update the template with the found interfaces
db_subst scoremaster-controller/interface interfaces "$INTERFACES"

# Ask the question
db_input high scoremaster-controller/interface || true
db_go || true
